"""empty message

Revision ID: 1880f3e6b81b
Revises: ff8f1dbbbad3
Create Date: 2021-02-20 11:34:01.046990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1880f3e6b81b'
down_revision = 'ff8f1dbbbad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('sexe', sa.String(), nullable=True))
    op.drop_column('prospect', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('prospect', 'sexe')
    # ### end Alembic commands ###
