"""empty message

Revision ID: 1af5ecbfe036
Revises: 46522fe768d4
Create Date: 2021-02-20 16:04:50.157700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af5ecbfe036'
down_revision = '46522fe768d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Agenda', 'Client', ['clien_t'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Destinataire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Locataire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Proprietaire'], ['id'])
    op.create_foreign_key(None, 'Mission', 'Client', ['Reference_BAILLEUR'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Mission', 'Client', ['Reference_LOCATAIRE'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Negotiateur_History', 'Client_negotiateur', ['negotiateur_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs_client', 'Client', ['reference_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_client', 'Client', ['client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suivi_client', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs_client', type_='foreignkey')
    op.drop_constraint(None, 'Negotiateur_History', type_='foreignkey')
    op.drop_constraint(None, 'Mission', type_='foreignkey')
    op.drop_constraint(None, 'Mission', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    # ### end Alembic commands ###
