"""empty message

Revision ID: 4c634d8dafbf
Revises: 465414d8ed72
Create Date: 2021-02-25 20:52:29.156606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c634d8dafbf'
down_revision = '465414d8ed72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agenda', sa.Column('Informations_generales', sa.String(), nullable=True))
    op.add_column('Agenda', sa.Column('Informations_reservees_service_planification', sa.String(), nullable=True))
    op.drop_column('Agenda', 'Informations_réservées_service_planification')
    op.drop_column('Agenda', 'Informations_générales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Agenda', sa.Column('Informations_générales', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Agenda', sa.Column('Informations_réservées_service_planification', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Agenda', 'Informations_reservees_service_planification')
    op.drop_column('Agenda', 'Informations_generales')
    # ### end Alembic commands ###
