"""empty message

Revision ID: 8827e94ec158
Revises: 86f0b6cd1e59
Create Date: 2021-02-14 09:25:39.904173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8827e94ec158'
down_revision = '86f0b6cd1e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Chiffrage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chiffrage',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Chiffrage_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Mission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Type_expert', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Pourcentage_gain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Chiffrage_pkey')
    )
    # ### end Alembic commands ###
