"""empty message

Revision ID: 8f942d739a7a
Revises: 
Create Date: 2021-01-18 16:30:16.920348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f942d739a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Agenda', 'Expert', ['Agent_referent_du_client'], ['id'])
    op.create_foreign_key(None, 'Agenda', 'Expert', ['audit_planner'], ['id'])
    op.create_foreign_key(None, 'Agenda', 'Client', ['clien_t'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Expert', ['expéditeur'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Proprietaire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Destinataire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Locataire'], ['id'])
    op.create_foreign_key(None, 'Tarifs', 'Client', ['reference_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    # ### end Alembic commands ###
