"""empty message

Revision ID: 92e92c4e479f
Revises: 8827e94ec158
Create Date: 2021-02-16 07:11:06.485098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e92c4e479f'
down_revision = '8827e94ec158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_client', sa.Column('visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_client', 'visibility')
    # ### end Alembic commands ###
