"""empty message

Revision ID: a91344953523
Revises: 43bc62b1c9ba
Create Date: 2021-03-11 09:31:55.956321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91344953523'
down_revision = '43bc62b1c9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturation_client', 'Email_de_relance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturation_client', sa.Column('Email_de_relance', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
