"""empty message

Revision ID: bb1db1e02677
Revises: 945d2c659180
Create Date: 2021-02-24 10:03:26.141961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb1db1e02677'
down_revision = '945d2c659180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturation', sa.Column('expediteur', sa.Integer(), nullable=True))
    op.drop_constraint('Facturation_expéditeur_fkey', 'Facturation', type_='foreignkey')
    op.create_foreign_key(None, 'Facturation', 'Expert', ['expediteur'], ['id'])
    op.drop_column('Facturation', 'expéditeur')
    op.drop_column('Mission', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mission', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Facturation', sa.Column('expéditeur', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.create_foreign_key('Facturation_expéditeur_fkey', 'Facturation', 'Expert', ['expéditeur'], ['id'])
    op.drop_column('Facturation', 'expediteur')
    # ### end Alembic commands ###
