"""empty message

Revision ID: cf590bc6f60c
Revises: 4c634d8dafbf
Create Date: 2021-02-26 08:04:03.840271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf590bc6f60c'
down_revision = '4c634d8dafbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturation_client', sa.Column('visibility', sa.Boolean(), nullable=True))
    op.add_column('facturation_mission', sa.Column('visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturation_mission', 'visibility')
    op.drop_column('facturation_client', 'visibility')
    # ### end Alembic commands ###
