"""empty message

Revision ID: ff8f1dbbbad3
Revises: 92e92c4e479f
Create Date: 2021-02-18 07:07:20.126592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8f1dbbbad3'
down_revision = '92e92c4e479f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Negotiateur_History', 'Client_negotiateur', ['negotiateur_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Negotiateur_History', type_='foreignkey')
    # ### end Alembic commands ###
