"""empty message

Revision ID: 1dcde88a77a7
Revises: 8f942d739a7a
Create Date: 2021-01-18 16:34:58.563407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcde88a77a7'
down_revision = '8f942d739a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Client', sa.Column('ZTF', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Client', 'ZTF')
    # ### end Alembic commands ###
