"""empty message

Revision ID: 465414d8ed72
Revises: bb1db1e02677
Create Date: 2021-02-25 13:35:26.106060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465414d8ed72'
down_revision = 'bb1db1e02677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturation_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_facture', sa.String(), nullable=True),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('Montant_HT', sa.String(), nullable=True),
    sa.Column('Montant_TTC', sa.String(), nullable=True),
    sa.Column('TTC', sa.String(), nullable=True),
    sa.Column('Date_de_creation', sa.String(), nullable=True),
    sa.Column('Date_reglement_client', sa.String(), nullable=True),
    sa.Column('Statut', sa.String(), nullable=True),
    sa.Column('Observations_suivi_paiement', sa.String(), nullable=True),
    sa.Column('Date_première_relance', sa.String(), nullable=True),
    sa.Column('Date_seconde_relance', sa.String(), nullable=True),
    sa.Column('Date_mise_en_demeure', sa.String(), nullable=True),
    sa.Column('Email_de_relance', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['Client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturation_mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_mission', sa.Integer(), nullable=True),
    sa.Column('fact_mission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fact_mission'], ['facturation_client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_mission'], ['Mission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturation_mission')
    op.drop_table('facturation_client')
    # ### end Alembic commands ###
