"""empty message

Revision ID: 675f9dca5708
Revises: 3c643552b2b4
Create Date: 2021-09-12 21:38:26.771276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675f9dca5708'
down_revision = '3c643552b2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Agenda', 'Client', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Agenda', 'Expert', ['Organisateur'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Agenda_expert', 'Expert', ['Participant_invité'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Facturation', 'Client', ['Proprietaire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Destinataire'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Expert', ['expediteur'], ['id'])
    op.create_foreign_key(None, 'Facturation', 'Client', ['Locataire'], ['id'])
    op.create_foreign_key(None, 'Facturation_history', 'Mission', ['mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'facturation_client', 'Client', ['client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'facturation_mission', 'Mission', ['ref_mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_client', 'Expert', ['responsable'], ['id'])
    op.create_foreign_key(None, 'suivi_client', 'Client', ['client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_prospect', 'prospect', ['prospect_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'suivi_prospect', 'Expert', ['responsable'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suivi_prospect', type_='foreignkey')
    op.drop_constraint(None, 'suivi_prospect', type_='foreignkey')
    op.drop_constraint(None, 'suivi_client', type_='foreignkey')
    op.drop_constraint(None, 'suivi_client', type_='foreignkey')
    op.drop_constraint(None, 'facturation_mission', type_='foreignkey')
    op.drop_constraint(None, 'facturation_client', type_='foreignkey')
    op.drop_constraint(None, 'Facturation_history', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Facturation', type_='foreignkey')
    op.drop_constraint(None, 'Agenda_expert', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    op.drop_constraint(None, 'Agenda', type_='foreignkey')
    # ### end Alembic commands ###
