"""empty message

Revision ID: af99adb3b0b6
Revises: c0300b6855ea
Create Date: 2021-08-30 21:51:56.985609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af99adb3b0b6'
down_revision = 'c0300b6855ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Facturation_history', 'Mission', ['mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'facturation_mission', 'Mission', ['ref_mission'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturation_mission', type_='foreignkey')
    op.drop_constraint(None, 'Facturation_history', type_='foreignkey')
    # ### end Alembic commands ###
