"""empty message

Revision ID: c0300b6855ea
Revises: 
Create Date: 2021-08-30 19:00:08.588535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0300b6855ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Client_email_key', 'Client', type_='unique')
    op.drop_constraint('Client_negotiateur_email_key', 'Client_negotiateur', type_='unique')
    op.drop_constraint('Expert_email_key', 'Expert', type_='unique')
    op.drop_constraint('prospect_email_key', 'prospect', type_='unique')
    op.create_foreign_key(None, 'suivi_prospect', 'prospect', ['prospect_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suivi_prospect', type_='foreignkey')
    op.create_unique_constraint('prospect_email_key', 'prospect', ['email'])
    op.create_unique_constraint('Expert_email_key', 'Expert', ['email'])
    op.create_unique_constraint('Client_negotiateur_email_key', 'Client_negotiateur', ['email'])
    op.create_unique_constraint('Client_email_key', 'Client', ['email'])
    # ### end Alembic commands ###
