"""empty message

Revision ID: f63511ab384f
Revises: a9cdf6847857
Create Date: 2021-01-19 19:54:22.323814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63511ab384f'
down_revision = 'a9cdf6847857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Reference', sa.String(), nullable=True),
    sa.Column('TYPE', sa.String(), nullable=True),
    sa.Column('SOCIETE', sa.String(), nullable=True),
    sa.Column('TITRE', sa.String(), nullable=True),
    sa.Column('NOM', sa.String(), nullable=True),
    sa.Column('EMAIL', sa.String(), nullable=True),
    sa.Column('NUMERO', sa.String(), nullable=True),
    sa.Column('ADRESSE1', sa.String(), nullable=True),
    sa.Column('ADRESSE2', sa.String(), nullable=True),
    sa.Column('CP', sa.String(), nullable=True),
    sa.Column('VILLE', sa.String(), nullable=True),
    sa.Column('Pays', sa.String(), nullable=True),
    sa.Column('abonnement', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('etat_client', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modif', sa.DateTime(), nullable=True),
    sa.Column('Numero_de_compte', sa.String(), nullable=True),
    sa.Column('Visibility', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Client', sa.Column('date_creation', sa.DateTime(), nullable=True))
    op.add_column('Client', sa.Column('date_modif', sa.DateTime(), nullable=True))
    op.add_column('Client', sa.Column('etat_client', sa.String(), nullable=True))
    op.add_column('Client', sa.Column('siret', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('Adresse1', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('Adresse2', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('Observations_de_suivi', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('actif_parti', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('code_tva', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('cp', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('date_certification_initiale', sa.DateTime(), nullable=True))
    op.add_column('Expert', sa.Column('date_entrée', sa.DateTime(), nullable=True))
    op.add_column('Expert', sa.Column('date_renouv_certification', sa.DateTime(), nullable=True))
    op.add_column('Expert', sa.Column('email_perso', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('login_backof', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('login_extranet', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('pwd_backof', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('pwd_extranet', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('pwd_gsuite', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('pwd_samsung', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('secteur_intervnention', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('siret', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('taux_tva', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('trigramme', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('type_certification', sa.String(), nullable=True))
    op.add_column('Expert', sa.Column('ville', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_AS_referent_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_AS_referent_client_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_agent_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_agent_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_respon_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_respon_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_suiveur_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_Planif_Ref_suiveur_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_devel_agent_suivi_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_devel_agent_suivi_client_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_devel_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_devel_respon_client_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_tech_Ref_agent_suivi_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_tech_Ref_respon_suivi_client_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_tech_Ref_suiveur_client', sa.Integer(), nullable=True))
    op.add_column('Tarifs', sa.Column('Cell_tech_Ref_suiveur_taux_com', sa.String(), nullable=True))
    op.add_column('Tarifs', sa.Column('maison_appartement', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_tech_Ref_agent_suivi_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_Planif_Ref_suiveur_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_devel_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_devel_agent_suivi_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_Planif_Ref_respon_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_AS_referent_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_Planif_Ref_agent_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Tarifs', 'Expert', ['Cell_tech_Ref_suiveur_client'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_constraint(None, 'Tarifs', type_='foreignkey')
    op.drop_column('Tarifs', 'maison_appartement')
    op.drop_column('Tarifs', 'Cell_tech_Ref_suiveur_taux_com')
    op.drop_column('Tarifs', 'Cell_tech_Ref_suiveur_client')
    op.drop_column('Tarifs', 'Cell_tech_Ref_respon_suivi_client_taux_com')
    op.drop_column('Tarifs', 'Cell_tech_Ref_agent_suivi_client')
    op.drop_column('Tarifs', 'Cell_devel_respon_client_taux_com')
    op.drop_column('Tarifs', 'Cell_devel_client')
    op.drop_column('Tarifs', 'Cell_devel_agent_suivi_client_taux_com')
    op.drop_column('Tarifs', 'Cell_devel_agent_suivi_client')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_suiveur_taux_com')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_suiveur_client')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_respon_taux_com')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_respon_client')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_agent_taux_com')
    op.drop_column('Tarifs', 'Cell_Planif_Ref_agent_client')
    op.drop_column('Tarifs', 'Cell_AS_referent_client_taux_com')
    op.drop_column('Tarifs', 'Cell_AS_referent_client')
    op.drop_column('Expert', 'ville')
    op.drop_column('Expert', 'type_certification')
    op.drop_column('Expert', 'trigramme')
    op.drop_column('Expert', 'taux_tva')
    op.drop_column('Expert', 'siret')
    op.drop_column('Expert', 'secteur_intervnention')
    op.drop_column('Expert', 'pwd_samsung')
    op.drop_column('Expert', 'pwd_gsuite')
    op.drop_column('Expert', 'pwd_extranet')
    op.drop_column('Expert', 'pwd_backof')
    op.drop_column('Expert', 'login_extranet')
    op.drop_column('Expert', 'login_backof')
    op.drop_column('Expert', 'email_perso')
    op.drop_column('Expert', 'date_renouv_certification')
    op.drop_column('Expert', 'date_entrée')
    op.drop_column('Expert', 'date_certification_initiale')
    op.drop_column('Expert', 'cp')
    op.drop_column('Expert', 'code_tva')
    op.drop_column('Expert', 'actif_parti')
    op.drop_column('Expert', 'Observations_de_suivi')
    op.drop_column('Expert', 'Adresse2')
    op.drop_column('Expert', 'Adresse1')
    op.drop_column('Client', 'siret')
    op.drop_column('Client', 'etat_client')
    op.drop_column('Client', 'date_modif')
    op.drop_column('Client', 'date_creation')
    op.drop_table('prospect')
    # ### end Alembic commands ###
